service: z36-api

plugins:
  - serverless-domain-manager
  
provider:
  name: aws
  region: us-east-2
  runtime: nodejs6.10
  memorySize: ${self:custom.memorySize}
  timeout: ${self:custom.timeout}
  stage: ${opt:stage, self:custom.defaultStage}
  profile: slsdev
  apiKeys:
    - dev-api
  environment:
    token: ${ssm:dev-token}
  
custom:
  memorySize: 128
  timeout: 10
  defaultStage: dev
  dev:
    profile: slsdev
    private: true
    domain: 'dev-api.z36.io'
  prod:
    profile: slsprod
    private: true
    domain: 'api.z36.io'
  private: ${self:custom.${self:provider.stage}.private}
  customDomain:
    basePath: ''
    domainName: ${self:custom.${self:provider.stage}.domain}
    stage: ${self:provider.stage}
  bucket: ${self:provider.stage}-z36-bucket

package:
  include:
    - components/**/*.*
    - functions/**/*.*
    - services/**/*.*

functions:
  index:
    memorySize: ${self:custom.memorySize}
    timeout: ${self:custom.timeout}
    handler: functions/index/function.handler
    events:
      - http:
          path: /
          method: get
          private: ${self:custom.private}
  public:
    memorySize: ${self:custom.memorySize}
    timeout: ${self:custom.timeout}
    handler: functions/public/function.handler
    events:
      - http:
          path: /public
          method: get
          cors: true
          private: false
