service: z36-db

plugins:
  - serverless-domain-manager
  
provider:
  name: aws
  region: us-east-2
  runtime: nodejs6.10
  memorySize: ${self:custom.memorySize}
  timeout: ${self:custom.timeout}
  stage: ${opt:stage, self:custom.defaultStage}
  profile: slsdev
  apiKeys:
    - dev-db
  environment:
    token: ${ssm:dev-token}
    table_transformations: ${self:custom.tables.transformations}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.table_transformations}'
  
custom:
  memorySize: 128
  timeout: 10
  defaultStage: dev
  dev:
    profile: slsdev
    private: true
    domain: 'dev-db.z36.io'
  prod:
    profile: slsprod
    private: true
    domain: 'db.z36.io'
  private: ${self:custom.${self:provider.stage}.private}
  customDomain:
    basePath: ''
    domainName: ${self:custom.${self:provider.stage}.domain}
    stage: ${self:provider.stage}
  bucket: ${self:provider.stage}-z36-bucket
  tables:
    transformations: ${self:provider.stage}-transformations

package:
  include:
    - components/**/*.*
    - functions/**/*.*
    - services/**/*.*

functions:
  index:
    memorySize: ${self:custom.memorySize}
    timeout: ${self:custom.timeout}
    handler: functions/index/function.handler
    events:
      - http:
          path: /
          method: get
          private: ${self:custom.private}
