service: z36-service

plugins:
  - serverless-domain-manager

provider:
  name: aws
  region: us-east-2
  memorySize: 128
  timeout: 10
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  
custom:
  defaultStage: dev
  profiles:
    dev: slsdev
  domains:
    dev: 'dev.z36.io'
  customDomain:
    basePath: ''
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${self:provider.stage}

functions:
  hello:
    memorySize: 128
    timeout: 10
    handler: api/home/handler.hello
    events:
      - http:
          path: /
          method: get