service: z36-web

plugins:
  - serverless-domain-manager
  - serverless-plugin-scripts
  
provider:
  name: aws
  region: us-east-2
  runtime: nodejs6.10
  memorySize: ${self:custom.memorySize}
  timeout: ${self:custom.timeout}
  stage: ${opt:stage, self:custom.defaultStage}
  profile: slsdev
  apiKeys: ${self:custom.${self:provider.stage}.apiKeys}
  environment:
    token: ${ssm:dev-token}
    api: ${self:custom.${self:provider.stage}.api}
  
custom:
  memorySize: 128
  timeout: 10
  defaultStage: dev
  dev:
    profile: slsdev
    apiKeys:
      - dev-web
    private: true
    domain: 'dev.z36.io'
    api: 'dev-api.z36.io'
  prod:
    profile: slsprod
    apiKeys:
      - prod-web
    private: false
    domain: 'z36.io'
    api: 'api.z36.io'
  private: ${self:custom.${self:provider.stage}.private}
  customDomain:
    basePath: ''
    domainName: ${self:custom.${self:provider.stage}.domain}
    stage: ${self:provider.stage}
  bucket: ${self:provider.stage}-z36-bucket
  scripts:
    commands:
      compile: npm run compile
    hooks:
      'deploy:initialize': sls compile
      'deploy:function:initialize': sls compile
  
package:
  include:
    - components/**/*.*
    - functions/**/*.*
    - pages/**/*.*
    - services/**/*.*

functions:
  index:
    memorySize: ${self:custom.memorySize}
    timeout: ${self:custom.timeout}
    handler: functions/index/function.handler
    events:
      - http:
          path: /
          method: get
          private: ${self:custom.private}
  transform:
    memorySize: ${self:custom.memorySize}
    timeout: ${self:custom.timeout}
    handler: functions/transform/function.handler
    events:
      - http:
          path: /transform
          method: get
          private: ${self:custom.private}
